version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node1
      - node2

  node1:
    build:
      context: ./node_backend
    environment:
      - PORT=3001
    depends_on:
      - fastapi
      - postgres

  node2:
    build:
      context: ./node_backend
    environment:
      - PORT=3002
    depends_on:
      - fastapi
      - postgres

  fastapi:
    build:
      context: ./fastapi_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dijia
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dijia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
